apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: etcd-staticpod 
  namespace: openshift-etcd
spec:
  selector:
    matchLabels:
      k8s-app: etcd-staticpod
  template:
    metadata:
      labels:
        name: etcd-staticpod
        k8s-app: etcd-staticpod
    spec:
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/master: ""
      priorityClassName: "system-cluster-critical"
      terminationGracePeriodSeconds: 3
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
        operator: Exists
      - key: node.kubernetes.io/not-ready
        effect: NoExecute
        operator: Exists
        tolerationSeconds: 120
      - key: node.kubernetes.io/unreachable
        effect: NoExecute
        operator: Exists
        tolerationSeconds: 120
      - key: node-role.kubernetes.io/etcd
        operator: Exists
        effect: NoSchedule
      containers:
      - image: "quay.io/openshift/cluster-etcd-operator:latest"
        imagePullPolicy: IfNotPresent
        name: etcd-credential-pusher
        command: ["cluster-etcd-operator", "credential-pusher"]
        args:
          - "--push-tls-secret=/etc/ssl/etcd/system:etcd-server:ETCD_DNS_NAME_FOR_THIS_NODE.crt,/etc/ssl/etcd/system:etcd-server:ETCD_DNS_NAME_FOR_THIS_NODE.key,openshift-etcd,etcd-serving-cert"
          - "--push-tls-secret=/etc/ssl/etcd/system:etcd-peer:ETCD_DNS_NAME_FOR_THIS_NODE.crt,/etc/ssl/etcd/system:etcd-peer:ETCD_DNS_NAME_FOR_THIS_NODE.key,openshift-etcd,etcd-peer-client-cert-${NODE_NAME}"
          - "--push-tls-secret=/etc/ssl/etcd/system:etcd-metric:ETCD_DNS_NAME_FOR_THIS_NODE.crt,/etc/ssl/etcd/system:etcd-metric:ETCD_DNS_NAME_FOR_THIS_NODE.key,etcd-metrics-proxy-serving-cert"
          - "--push-tls-secret=/etc/ssl/etcd/system:etcd-peer:ETCD_DNS_NAME_FOR_THIS_NODE.crt,/etc/ssl/etcd/system:etcd-peer:ETCD_DNS_NAME_FOR_THIS_NODE.key,openshift-etcd,etcd-metrics-proxy-peer-client-cert"
          - "--push-ca-bundle=/etc/ssl/etcd/ca.crt,openshift-etcd,etcd-serving-ca"
          - "--push-ca-bundle=/etc/ssl/etcd/ca.crt,openshift-etcd,etcd-peer-client-ca"
          - "--push-ca-bundle=/etc/ssl/etcd/ca.crt,openshift-etcd,etcd-metrics-proxy-serving-ca"
          - "--push-ca-bundle=/etc/ssl/etcd/metric-ca.crt,openshift-etcd,etcd-metrics-proxy-client-ca"
        serviceAccount: default
        terminationMessagePolicy: FallbackToLogsOnError
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - mountPath: /etc/ssl/etcd/
          name: certs
        resources:
          requests:
            cpu: 10m
            memory: 5Mi
      volumes:
      - hostPath:
          path: /etc/kubernetes/static-pod-resources/etcd-member
          type: ""
        name: certs
